### ISSUE TITLE
スナックワールド トレジャラーズのセーブデータ編集ツールの置き場

### ISSUE THREAD

**Issue by yroyro2444** [togenyan/SWE#1]
はじめまして。
妖怪ウォッチの頃から使わせていただいております。ありがとうございます。
早速ですが、本編集ツールがどこからDLできるかわかりません。
妖怪ウォッチの時はreleasesのところにあったのですが。
初歩的な質問で恐縮ですが宜しくおねがいします。

**Comment by togenyan** [comment]
つい先ほどリリースしたので、そちらからダウンロードしてください。

**Comment by yroyro2444** [comment]
ご対応ありがとうございました。
